let lessons = [
    {
        id: 1,
        subject: "Math",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 2,
        subject: "IT",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 3,
        subject: "Polski",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 4,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 5,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 6,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 7,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 8,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 9,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 10,
        subject: "Matematyka",
        location: "Hendon",
        price: 1000,
        image: "img/Math.png",
        availableInventory : 5,
        spaces: 5,
    },


]