let lessons = [
    {
        id: 1,
        subject: "Maths Classes",
        location: "Hendon",
        price: 50,
        image: "img/Math.png",
        availableInventory : 10,
        spaces: 10,
    },
    {
        id: 2,
        subject: "Programming",
        location: "Hendon",
        price: 50,
        image: "img/IT.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 3,
        subject: "History Classes",
        location: "Hendon",
        price: 30,
        image: "img/History.png",
        availableInventory : 15,
        spaces: 15,
    },
    {
        id: 4,
        subject: "Business",
        location: "Hendon",
        price: 25,
        image: "img/Business.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 5,
        subject: "Basketball Club",
        location: "Hendon",
        price: 10,
        image: "img/Basketball.png",
        availableInventory : 7,
        spaces: 7,
    },
    {
        id: 6,
        subject: "Football Club",
        location: "Hendon",
        price: 10,
        image: "img/Football.jpg",
        availableInventory : 10,
        spaces: 10,
    },
    {
        id: 7,
        subject: "Philosophy",
        location: "Hendon",
        price: 20,
        image: "img/Philosophy.jpg",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 8,
        subject: "Literature Club",
        location: "Hendon",
        price: 20,
        image: "img/Literature.png",
        availableInventory : 20,
        spaces: 20,
    },
    {
        id: 9,
        subject: "Chemistry",
        location: "Hendon",
        price: 35,
        image: "img/Chemistry.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 10,
        subject: "Physics",
        location: "Hendon",
        price: 25,
        image: "img/Physics.jpg",
        availableInventory : 10,
        spaces: 10,
    },


]